SELECT * FROM STORE;
SELECT * FROM USER;
SELECT * FROM REVIEW;
SELECT * FROM WISHLIST_GAME;
SELECT * FROM WISHLIST_GAME_PRICE_TIMELINE;
SELECT * FROM PRICE_TIMELINE;
SELECT * FROM SECRET_VARIABLES;
SELECT * FROM STEAM_GAMES;
SELECT * FROM GAME_GENRE;
SELECT * FROM GENRE;
SELECT * FROM GAME;
SELECT * FROM DEVELOPER;



SELECT * FROM REVIEW;
INSERT INTO REVIEW (ID_USER,ID_GAME,RATING,REVIEW) VALUES
(1,2,9,'ASD') ON DUPLICATE KEY UPDATE
RATING = 7, REVIEW = 'FGH';
        
        
        
        
        