SELECT * FROM STORE;
SELECT * FROM USER;
SELECT * FROM REVIEW;
SELECT * FROM WISHLIST_GAME;
SELECT * FROM WISHLIST_GAME_PRICE_TIMELINE;
SELECT * FROM PRICE_TIMELINE;
SELECT * FROM SECRET_VARIABLES;
SELECT * FROM STEAM_GAMES;
SELECT * FROM GAME_GENRE;
SELECT * FROM GENRE;
SELECT * FROM GAME;
SELECT * FROM DEVELOPER;

		SELECT 
			DISTINCT(TIME), WGPT.URL, PT.PRICE, PT.DISCOUNT, WGPT.NAME, ST.URL AS URL_STORE
		FROM 
			PRICE_TIMELINE PT, WISHLIST_GAME WG, STORE ST, WISHLIST_GAME_PRICE_TIMELINE WGPT
		WHERE
			WGPT.ID = WG.ID_URL AND
		    PT.ID_URL = WGPT.ID AND
			WGPT.ID_STORE = ST.ID AND
			WGPT.URL = '/game/witcher_adventure_game';
  
        
        
        
        
        
        
        
        
        