CREATE DATABASE MYGAMEWISHLIST;
USE MYGAMEWISHLIST;
#DROP DATABASE MYGAMEWISHLIST;

CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    ADMIN INT(1) DEFAULT 0,
    PRIMARY KEY(ID)
);

CREATE TABLE STORE(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    URL VARCHAR(256) UNIQUE NOT NULL,
    QUERY_PART VARCHAR(128) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE GAME(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) UNIQUE,
    DESCRIPTION VARCHAR(256),
    PRIMARY KEY(ID)
);

CREATE TABLE LIST(
    ID INT AUTO_INCREMENT,
	ID_USER INT,
    PRIMARY KEY(ID, ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

DELIMITER $$
CREATE TRIGGER ADD_LIST AFTER INSERT ON USER
	FOR EACH ROW
    BEGIN
		INSERT INTO LIST (ID_USER) VALUES(NEW.ID);
	END$$
DELIMITER ;

CREATE TABLE WISHLIST_GAME(
	URL VARCHAR(256),
    ID_LIST INT,
    ID_STORE INT NOT NULL,
    IMG VARCHAR(256) DEFAULT "",
    NAME VARCHAR(32) NOT NULL,
    DEFAULT_PRICE DECIMAL(5,2) NOT NULL,
    CURRENT_PRICE DECIMAL(5,2) NOT NULL,
    LAST_NOTIFIED_PRICE DECIMAL(5,2) DEFAULT -1,    
    MIN_PRICE DECIMAL(5,2) DEFAULT -1,
    MAX_PRICE DECIMAL(5,2) DEFAULT -1,
    PRIMARY KEY(URL, ID_LIST),
    FOREIGN KEY (ID_LIST) REFERENCES LIST(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_STORE) REFERENCES STORE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REVIEW(
	ID_USER INT,
    ID_GAME INT,
    RATING INT(2) NOT NULL,
    PRIMARY KEY(ID_USER, ID_GAME),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SECRET_VARIABLES(
	NAME VARCHAR(16),
    VALUE VARCHAR(64),
    PRIMARY KEY(NAME)
);

CREATE TABLE STEAM_GAMES(
	APPID INT,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY(APPID)
);