CREATE DATABASE MYGAMEWISHLIST;
USE MYGAMEWISHLIST;
#DROP DATABASE MYGAMEWISHLIST;

CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    ADMIN INT(1) DEFAULT 0,
    PRIMARY KEY(ID)
);

CREATE TABLE SHOP(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    URL VARCHAR(256) UNIQUE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE GAME(
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(32) UNIQUE,
    DESCRIPTION VARCHAR(256),
    PRIMARY KEY(ID)
);

CREATE TABLE LIST(
    ID INT AUTO_INCREMENT,
	ID_USER INT,
    PRIMARY KEY(ID, ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE WISHLIST_GAME(
	URL VARCHAR(256),
    ID_USER INT,
    ID_SHOP INT,
    NAME VARCHAR(32) NOT NULL,
    DEFAULT_PRICE DECIMAL(5,2) NOT NULL,
    CURRENT_PRICE DECIMAL(5,2) NOT NULL,
    LAST_NOTIFIED_PRICE DECIMAL(5,2) DEFAULT -1,    
    MIN_PRICE DECIMAL(5,2) DEFAULT -1,
    MAX_PRICE DECIMAL(5,2) DEFAULT -1,
    PRIMARY KEY(URL, ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES LIST(ID_USER) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SHOP) REFERENCES SHOP(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REVIEW(
	ID_USER INT,
    ID_GAME INT,
    RATING INT(2) NOT NULL,
    PRIMARY KEY(ID_USER, ID_GAME),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
